language: rust
rust:
- stable
- beta
- nightly
notifications:
  email:
  - mitchell.nordine@gmail.com
os:
- osx
env:
  matrix:
  - LD_LIBRARY_PATH: /usr/local/lib
  global:
  - secure: URNNlOqxnfwWDC/w4PDTCswqe9ccnkIqDwfQecppfEui4KhpYXfrG9gx3xupWzWMfX+NPEcXtiyWA4CuUYaHbWWINLeLQUk650AFEqaRSiTpeh45Y9nh3dHT4fFDz4OeNfayNBBKL0kx5YwrugoeQggIgnF2KEcIHMF0+BbTtAM=
install:
- rustup target add aarch64-apple-ios x86_64-apple-ios
before_script:
- rustc --version
- cargo --version
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --verbose
- cargo build --verbose --target aarch64-apple-ios
- cargo build --verbose --target x86_64-apple-ios
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=coreaudio/index.html>" > target/doc/index.html &&
  pip install --user ghp-import &&
  ghp-import -n target/doc &&
  # Redirect any output to `/dev/null` to hide any sensitive
  # credential data that might otherwise be exposed.
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages > /dev/null 2>&1
